### ISSUE TITLE
What are the use cases for HITCOUNT_HITS_PER_IP_LIMIT and HITCOUNT_HITS_PER_SESSION_LIMIT?

### ISSUE THREAD

**Issue by pmi123** [abhiabhi94/dj-hitcount#31]
Please help me understand the real world usage of the following options:

1. HITCOUNT_HITS_PER_IP_LIMIT
I don't understand the use cases for "Only count 3 hits from IP xxx.xxx.xxx.xxx, and then no more." I understand the use case for blocking a specific IP, but not for limiting the counting of hits from a specific IP to an arbitrary upper limit.

3. HITCOUNT_HITS_PER_SESSION_LIMIT
I don't understand the use of this parameter, either. What is the use case for saying "Only count 3 hits from this session, then no more."

Thanks!

Mark

**Comment by abhiabhi94** [comment]
Let me try to recall, it been pretty long since i worked on this project.

One of the rationales that come to my mind are, you want to count just one count from a set of IPs(may be your locally group of editors for a blogging website).
