### ISSUE TITLE
Does not work with Django 3.2.5 

### ISSUE THREAD

**Issue by Aneemes** [abhiabhi94/dj-hitcount#37]
Trying to replace the django-hitcount library with dj-hitcount on my project, I get the same issue I got while using django-hitcount==1.3.5 ,following exception:
Exception Type: DataError at /documents/detail/0f40bfe6-a49b-4209-b8fa-858a691b591c/
Exception Value: integer out of range

**Comment by abhiabhi94** [comment]
hey @Aneemes, thanks for the issue. i'm sorry but i can do very little without a minimal reproducible example.

thanks.

**Comment by Aneemes** [comment]
I resolved it. So, the object_pk was only taking PositiveIntegerField but my project had object_id as UUID. Anyone looking for django-hitcout to support UUID can use the following forked repo:
https://github.com/Aneemes/django-hitcount.git
